### ISSUE TITLE
"M" turned "H"

### ISSUE THREAD

**Issue by EWNB** [Harbys/pico-ssd1306#14]
It seems that the letter "M" has been substituted in the `5x8_font` with the letter "H".

The cause seems to be that the following data appears twice in each `#ifndef` or `#else` section in `5x8_font.h`,  once for "H" (as it should) and again for "M":

```
        0x7c,
        0x10,
        0x10,
        0x7c,
        0x0,
```

Note that the 'ndef' `SSD1306_ASCII_FULL` entries have trailing whitespace but the `SSD1306_ASCII_FULL` entries don't, which can screw with non-regexp file contents searches.

**Comment by Harbys** [comment]
It's an issue with the font width itself. in a 5 (width) x 8(height) pixels font one pixel of width is reserved for spacing between letters (and for drawing special characters). So you are left with 4 pixels of usable width so there is no way of distinguishing M from H as there is no way of creating a V shape with 2 pixels. You would need to create a 6x8 font to solve this issue

As for trailing whitespaces seems that this file got never formatted. will fix
