### ISSUE TITLE
Allow the Facility to Turn Display On or Off

### ISSUE THREAD

**Issue by bdhar1** [Harbys/pico-ssd1306#16]
The current driver does not have the facility to turn the display off so as to allow screensaver like feature. It would be nice to add this feature to the library.

**Comment by bdhar1** [comment]
Added pull request #17 with the change for your review.

**Comment by Harbys** [comment]
I made a reply in the PR itself. Please refer to #17

**Comment by Harbys** [comment]
Merged in #17
