### ISSUE TITLE
Issue building the Lib

### ISSUE THREAD

**Issue by ort111** [Harbys/pico-ssd1306#18]
Have everything setup, but when building the lib getting
--------
In file included from /Users/jeffo/desktop/dev/weather/pico-ssd1306-master/textRenderer/TextRenderer.cpp:1:
In file included from /Users/jeffo/desktop/dev/weather/pico-ssd1306-master/textRenderer/TextRenderer.h:4:
/Users/jeffo/desktop/dev/weather/pico-ssd1306-master/textRenderer/../ssd1306.h:5:10: fatal error: 'hardware/i2c.h' file not found
#include "hardware/i2c.h"
         ^~~~~~~~~~~~~~~~
1 error generated.
----------
the pico SDK is setup and the env var is setup correctly.  Have tried a few things with CMakeLists.txt with no luck.  Trying to build the examples for basic text.  Any help / direction would be appreciated.

**Comment by ort111** [comment]
I got this to work with some small changes in the cmake lists file, thanks

**Comment by Harbys** [comment]
From the last comment I understand that you got it working? Can this issue be closed?

**Comment by ort111** [comment]
Yes
