### ISSUE TITLE
#pragma once and #ifdef/#define are redundant

### ISSUE THREAD

**Issue by FunMiles** [Harbys/pico-ssd1306#7]
Every include file starts with `#pragma once` and continues with `#ifndef FILENAME_H` and `#define FILENAME_H`
The two methods do fundamentally the same thing. 
I would remove the #ifndef / #define / #endif as it is more verbose and supposedly, #pragma once can be more efficient.
Supposedly, not all compilers have supported #pragma once, but GCC and Clang do and I have yet to encounter a modern compiler that does not. The pico SDK uses GCC, so even if some exotic compiler does not like #pragma once, it is not an issue for this project.

**Comment by Harbys** [comment]
I left it in as it was auto generated by my IDE. I'll look into it in a couple of days

**Comment by FunMiles** [comment]
My IDE used to generate only the `#ifndef version`. I modified its template to only generate `#pragma once`. You might consider doing likewise.

**Comment by Harbys** [comment]
Ok, so this was fixed a while back with no issues.
